In [1]:
import torch

In [3]:

t1 = torch.arange(2, 11).float()
t2 = torch.arange(21, 25, 0.5).float().view(1, 8)
t3 = torch.arange(0, -2, -0.2).float().view(5, 2)


In [5]:
t1 = torch.linspace(3, 5, 3).float()
t2 = torch.linspace(9, -9, 10).float()
t3 = torch.linspace(5, -5, 5).float().view(5, 1)

In [20]:
t1 = torch.rand(21).float()
t2 = torch.randint(-5, 6, (3, 5), dtype=torch.int16)
t3 = torch.randn((64, 128), dtype=torch.float64)

t1 = torch.Tensor(3, 10, 2).uniform_(-2, 10)
t2 = torch.Tensor(123).random_(13, 20)
t3 = torch.Tensor(8, 1024).normal_(mean=23, std=50)

In [27]:
t_indx = torch.arange(1, 65).view(2, 32)

In [ ]:
t1 = torch.empty(3, 2, 10).fill_(5)
t2 = torch.empty(1, 10, 1, 7, 1).fill_(-1)

t1.unsqueeze_(dim=0)
t2.squeeze_()

torch.Size([10, 7])

In [32]:
tr = torch.zeros(32).int()
tr[0] = tr[-1] = -1

In [41]:
lst = list(map(float, input().split())) # список в программе не менять

tr = torch.tensor(lst)
tr_2 = tr[torch.arange(0, tr.shape[0], 2)]
print(*[round(xx.item(), 1) for xx in tr_2])

0.1 -1.2 0.5


In [45]:
# списки lst_1 и lst_2 в программе не менять
lst_1 = list(map(int, input().split()))
lst_2 = list(map(int, input().split()))

t1 = torch.tensor(lst_1, dtype=torch.int32)
t2 = torch.tensor(lst_2, dtype=torch.int32)

t1[1:t2.shape[0]+1] = t2
print(*t1.tolist())

1 7 6 5 4 6 7 8 9


In [ ]:

tr3d = torch.tensor([torch.arange(1, 13).view(3, 4).tolist(), torch.arange(10, 130, 10).view(3, 4).tolist(), torch.arange(-1, -13, -1).view(3, 4).tolist()], dtype=torch.int16)
tm = tr3d[1, ...]
tm

tensor([[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])

In [64]:

lst = list(map(int, input().split())) # список lst в программе не менять

tr3d = torch.tensor(lst, dtype=torch.int16).view(3, 3, 4)
t_res = tr3d[:, 1, :]

RuntimeError: shape '[3, 3, 4]' is invalid for input of size 0

In [66]:
lst = list(map(int, input().split())) # список lst в программе не менять

tr = torch.tensor(lst, dtype=torch.int32)
t_res = tr[(tr >= -2) & (tr <= 2)]

In [ ]:
# списки в программе не менять
lst_1 = list(map(int, input().split()))
lst_2 = list(map(int, input().split()))

tr1 = torch.tensor(lst_1).int()
tr2 = torch.tensor(lst_2).int()

tr1.resize_(min(tr1.shape[0], tr2.shape[0]))
tr2.resize_(min(tr1.shape[0], tr2.shape[0]))

tr1 **= tr2

tensor([  1,  32, 729], dtype=torch.int32)

In [23]:
lst = list(map(float, input().split())) # список lst в программе не менять

t_mask = torch.ones(16, dtype=torch.int8)
t_mask[torch.arange(1, t_mask.shape[0], 2)] = -1
tr = torch.tensor(lst)
tr.mul_(t_mask.to(torch.float32))
tr = torch.round(tr, decimals=2)
tr

ValueError: could not convert string to float: '5,'

In [27]:
lst = list(map(int, input().split())) # список lst в программе не менять

targets = torch.tensor(lst).int()
t_onehot = torch.zeros(targets.shape[0], torch.max(targets) + 1, dtype=torch.int8)
t_onehot[torch.arange(targets.shape[0]), lst] = 1
t_onehot

tensor([[1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0]], dtype=torch.int8)